#!/usr/bin/env python3
"""The hand-written conversation database. Each entry is
(category, who, mood, text). who: pilot | vendor | any. mood: a
personality (gruff, cheerful, nervous, formal, sly) or any.

Slots filled at runtime: {name} the speaker, {system} the current system,
{star} its star kind, {station} the speaker's station or the nearest one,
{commodity} and {units} the pilot's cargo, {dest} and {dest_price} where it
is going and what it fetches there, {origin} where it was bought, {ship}
the speaker's hull, {hull} the player's hull, {credits} the player's
credits, {nearby} a linked system, {want} what the market is short of,
{glut} what it has too much of, {price} the price on the table.

    python3 tools/dialog_lines.py   # writes assets/dialog/lines.json
"""
import json, os

L = [
    # ------------------------------------------------------------ greeting: pilot
    ("greeting", "pilot", "gruff", "What. I'm busy. Say it quick."),
    ("greeting", "pilot", "gruff", "You docked without so much as a hello. Fine. Talk."),
    ("greeting", "pilot", "gruff", "{name}. This is my ship. Mind the deck plates."),
    ("greeting", "pilot", "gruff", "Another {hull} pilot with time to burn. Well, I don't have any. Make it count."),
    ("greeting", "pilot", "cheerful", "Hey! Company out here, what are the odds. {name}, pleased to meet you."),
    ("greeting", "pilot", "cheerful", "Welcome aboard the {ship}! Watch the third rung, it bites. I'm {name}."),
    ("greeting", "pilot", "cheerful", "Oh, a visitor! I was talking to the nav computer again. It never answers. Sit, sit."),
    ("greeting", "pilot", "cheerful", "You picked a good day, I just brewed something that is nearly coffee."),
    ("greeting", "pilot", "nervous", "You're not... you're not with the collections office, are you? No? Good. Good. {name}."),
    ("greeting", "pilot", "nervous", "I saw you coming for hours. Kept thinking, what do they want. So. What do you want?"),
    ("greeting", "pilot", "nervous", "Please don't touch anything. Half of it is held together with tape and hope."),
    ("greeting", "pilot", "nervous", "Hello. Hi. Sorry. I don't get many people docking. Is something wrong with my orbit?"),
    ("greeting", "pilot", "formal", "Captain. {name}, master of the {ship}. State your business and be welcome."),
    ("greeting", "pilot", "formal", "Permission to come aboard was granted; I trust the transfer was smooth."),
    ("greeting", "pilot", "formal", "Good day. We keep a tidy ship here. I would ask you to do the same."),
    ("greeting", "pilot", "formal", "You have the courtesy to match velocities properly. That already puts you ahead of most."),
    ("greeting", "pilot", "sly", "Well now. A {hull} that can actually rendezvous. You're either good or lucky. Which is it?"),
    ("greeting", "pilot", "sly", "{name}. Don't believe anything the other pilots say about me. Most of it, anyway."),
    ("greeting", "pilot", "sly", "Come in. Mind the crate by the hatch. Don't ask what's in it."),
    ("greeting", "pilot", "sly", "A visitor. I'll assume you want something. Everyone does. Let's see if it's something I've got."),
    # ------------------------------------------------------------ greeting: vendor
    ("greeting", "vendor", "gruff", "Prices are on the board. I don't do discounts and I don't do stories."),
    ("greeting", "vendor", "gruff", "{station} market. Buy, sell, or get out of the queue."),
    ("greeting", "vendor", "gruff", "You want {want}? Everybody wants {want}. Get in line."),
    ("greeting", "vendor", "gruff", "The scales are honest. That's more than I can say for the last three captains through here."),
    ("greeting", "vendor", "cheerful", "Welcome to {station}! Best stock in {system}, and I'd say that even if it weren't true."),
    ("greeting", "vendor", "cheerful", "A new face! Come look at the boards, we got a shipment in and the {glut} is practically free."),
    ("greeting", "vendor", "cheerful", "Sit down, have a look, nobody leaves {station} without at least a story."),
    ("greeting", "vendor", "cheerful", "You look like someone who needs {want} and I look like someone who wishes she had it. Let's talk anyway."),
    ("greeting", "vendor", "nervous", "Oh. Hello. The, um, the manifest is right here. Everything's counted. Twice."),
    ("greeting", "vendor", "nervous", "Welcome. Please don't lean on the counter, the last one collapsed."),
    ("greeting", "vendor", "nervous", "If you're here about the {glut} shipment, I swear I didn't order that much."),
    ("greeting", "vendor", "nervous", "Hello! Sorry. Quiet shift. I jump at every hatch cycle."),
    ("greeting", "vendor", "formal", "{station} exchange. {name}, at your service. The current tariffs are posted."),
    ("greeting", "vendor", "formal", "Good day, captain. We trade at the listed rates and settle on the spot."),
    ("greeting", "vendor", "formal", "Welcome to {station}. Our books are open to any captain in good standing."),
    ("greeting", "vendor", "formal", "You'll find our prices fair and our scales calibrated this morning."),
    ("greeting", "vendor", "sly", "Ah, a captain with credits. I can always tell. {name}. What can I part you from?"),
    ("greeting", "vendor", "sly", "Everything's for sale at {station}. Some of it's even on the manifest."),
    ("greeting", "vendor", "sly", "Come in, come in. The prices on the board are for people who don't ask nicely."),
    ("greeting", "vendor", "sly", "Between us, the {want} price is going to climb. I'd act before the next ship docks."),
    # ------------------------------------------------------------ small talk
    ("smalltalk", "any", "gruff", "Weather? There's no weather. There's vacuum and there's the {star}. Pick one."),
    ("smalltalk", "any", "gruff", "I've been flying since before your hull was a spreadsheet."),
    ("smalltalk", "any", "gruff", "Talk is cheap. Propellant isn't."),
    ("smalltalk", "any", "gruff", "{system}. Same rocks, same prices, same complaints. Suits me."),
    ("smalltalk", "any", "gruff", "You want conversation, buy a radio drama."),
    ("smalltalk", "any", "gruff", "The one thing I miss about planets is that things stay where you put them."),
    ("smalltalk", "any", "cheerful", "Have you seen {system} from the outer edge? The {star} looks like a coin someone dropped."),
    ("smalltalk", "any", "cheerful", "I name every ship I meet. Yours is definitely a Gerald."),
    ("smalltalk", "any", "cheerful", "My grandmother said never trust a pilot who doesn't hum. I hum constantly."),
    ("smalltalk", "any", "cheerful", "Long orbits are the best part. Nothing to do but think and eat the good rations first."),
    ("smalltalk", "any", "cheerful", "Did you know {nearby} has a station that plays music over the docking channel? Awful music. I love it."),
    ("smalltalk", "any", "cheerful", "I keep a plant in the cockpit. It's doing better than I am."),
    ("smalltalk", "any", "nervous", "Do you ever hear the hull tick? It's just thermal. It's definitely just thermal."),
    ("smalltalk", "any", "nervous", "I checked the periapsis four times before you docked. It's fine. It's fine."),
    ("smalltalk", "any", "nervous", "They say the {star} has been quiet lately. Quiet is good. Quiet is when things build up."),
    ("smalltalk", "any", "nervous", "I don't sleep at warp. Everyone says it's safe. Everyone said a lot of things."),
    ("smalltalk", "any", "nervous", "Sorry, I talk fast when I'm docked. Undocked I don't talk at all."),
    ("smalltalk", "any", "nervous", "Is your hull rated for {star} systems? Mine says it is. It says a lot of things."),
    ("smalltalk", "any", "formal", "A well-kept orbit is the mark of a well-kept mind, my instructor used to say."),
    ("smalltalk", "any", "formal", "I log every burn. Not because anyone reads it. Because I would know if I didn't."),
    ("smalltalk", "any", "formal", "{system} is a respectable system. The tariffs are predictable, which is all one can ask."),
    ("smalltalk", "any", "formal", "The {star} here throws a hard glare on approach. Do mind your heat line."),
    ("smalltalk", "any", "formal", "I have flown {nearby} to {system} more times than I care to count. It never gets shorter."),
    ("smalltalk", "any", "formal", "One learns patience out here or one learns nothing."),
    ("smalltalk", "any", "sly", "Every pilot has a story about a slingshot that nearly killed them. Mine's better. It nearly killed someone else."),
    ("smalltalk", "any", "sly", "Rules of the lane: keep your Δv, keep your mouth shut, keep a spare hatch key."),
    ("smalltalk", "any", "sly", "I don't gamble. I invest in outcomes I already know."),
    ("smalltalk", "any", "sly", "You'd be amazed what people leave in docking bays. I have a collection."),
    ("smalltalk", "any", "sly", "The trick in {system} is to be leaving when everyone else is arriving."),
    ("smalltalk", "any", "sly", "Between you and me, the customs scans at {station} only look at the top crate."),
    ("smalltalk", "any", "any", "Lot of traffic through {system} lately. Or maybe I'm just noticing it more."),
    ("smalltalk", "any", "any", "How's the {hull} treating you? Mine rattles above half throttle."),
    ("smalltalk", "any", "any", "You ever count the stars on a long coast? I get to about two hundred and give up."),
    ("smalltalk", "any", "any", "They keep saying they'll fix the beacons out past {nearby}. They keep not doing it."),
    # ------------------------------------------------------------ rumours: pilot
    ("rumour", "pilot", "gruff", "{commodity} is going for {dest_price} at {dest}. Don't tell me you didn't hear it from me."),
    ("rumour", "pilot", "gruff", "{origin} is drowning in {commodity}. That's why I've got a hold full of it."),
    ("rumour", "pilot", "gruff", "{dest} pays. That's the whole rumour."),
    ("rumour", "pilot", "cheerful", "Oh! {dest} is paying {dest_price} for {commodity} right now. That's why I'm grinning."),
    ("rumour", "pilot", "cheerful", "Word is {nearby} has been short of everything since a freighter went missing. Sad, but, you know. Prices."),
    ("rumour", "pilot", "cheerful", "Everyone's running {commodity} out of {origin} this week. Get in before it's a glut!"),
    ("rumour", "pilot", "nervous", "I heard... I heard {dest} is paying {dest_price} for {commodity}. Don't crowd me on it. Please."),
    ("rumour", "pilot", "nervous", "Someone said the heat line at the {star} is wider than the charts say. I gave it extra room."),
    ("rumour", "pilot", "nervous", "There's talk of a shortage at {nearby}. Talk. Just talk. Probably."),
    ("rumour", "pilot", "formal", "For your information: {dest} is currently offering {dest_price} per unit of {commodity}."),
    ("rumour", "pilot", "formal", "{origin} is oversupplied with {commodity}. It will not last, but it is true today."),
    ("rumour", "pilot", "formal", "{nearby} has raised its tariffs again, I am told. Plan accordingly."),
    ("rumour", "pilot", "sly", "A little bird says {dest} pays {dest_price} for {commodity}. The bird wants a finder's fee."),
    ("rumour", "pilot", "sly", "Buy {commodity} at {origin} and sell it at {dest}. Or don't. More for me."),
    ("rumour", "pilot", "sly", "There's a shipyard in {nearby} selling hulls below cost. Ask me how I know. Actually, don't."),
    # ------------------------------------------------------------ rumours: vendor
    ("rumour", "vendor", "gruff", "We're short of {want}. Bring some and I'll pay. That's not a rumour, that's the board."),
    ("rumour", "vendor", "gruff", "Too much {glut} in the back. Take it off my hands and I'll remember you."),
    ("rumour", "vendor", "gruff", "{nearby}'s prices are a joke. Ours aren't."),
    ("rumour", "vendor", "cheerful", "We are desperate for {want}! Desperate! I'd sell my chair for a hold of it."),
    ("rumour", "vendor", "cheerful", "Pilots keep coming in from {nearby} saying it's booming over there. Booming!"),
    ("rumour", "vendor", "cheerful", "The {glut} is cheap this week. Cheap cheap. Fill your hold and thank me later."),
    ("rumour", "vendor", "nervous", "We're running low on {want}. If someone doesn't bring some soon I have to explain it upstairs."),
    ("rumour", "vendor", "nervous", "I heard a ship broke up near the {star}. Nobody official said anything. That's what worries me."),
    ("rumour", "vendor", "nervous", "The {glut} keeps piling up. I don't know where it's coming from. I've stopped asking."),
    ("rumour", "vendor", "formal", "{station} is currently under-supplied in {want}; sellers will find our rate generous."),
    ("rumour", "vendor", "formal", "Reports from {nearby} suggest their markets have moved considerably. I would verify before committing."),
    ("rumour", "vendor", "formal", "We hold a surplus of {glut}. Buyers may take advantage while it lasts."),
    ("rumour", "vendor", "sly", "Bring {want}. I'll pay over the board and we'll both pretend I didn't."),
    ("rumour", "vendor", "sly", "There's a captain who buys {glut} at {nearby} without checking the grade. Just saying."),
    ("rumour", "vendor", "sly", "The board says one price. My cousin at {nearby} says another. One of us is lying."),
    # ------------------------------------------------------------ pilot cargo talk
    ("cargo", "pilot", "gruff", "{units} units of {commodity}. Bought at {origin}, headed for {dest}. Any other questions?"),
    ("cargo", "pilot", "gruff", "Hold's full of {commodity}. It's not for admiring."),
    ("cargo", "pilot", "gruff", "It's {commodity}. Don't ask me what it's used for, ask me what it pays."),
    ("cargo", "pilot", "cheerful", "{units} units of {commodity}! Beautiful stuff. Well, it's crates. But the numbers are beautiful."),
    ("cargo", "pilot", "cheerful", "Running {commodity} from {origin} to {dest}. It's not glamorous, but it's honest and it's mine."),
    ("cargo", "pilot", "cheerful", "I've got {commodity} aboard and I've grown quite fond of it. Don't tell {dest}."),
    ("cargo", "pilot", "nervous", "It's {commodity}. Just {commodity}. {units} units. All properly stowed. I checked."),
    ("cargo", "pilot", "nervous", "I'm carrying {commodity} to {dest}. If I make it. When I make it. I'll make it."),
    ("cargo", "pilot", "nervous", "It's {commodity}, from {origin}. Legitimately. I have the receipts. Do you want to see the receipts?"),
    ("cargo", "pilot", "formal", "The manifest reads {units} units of {commodity}, consigned to {dest}."),
    ("cargo", "pilot", "formal", "Just {commodity}, loaded at {origin}. A routine run. Routine is the goal."),
    ("cargo", "pilot", "formal", "I carry {commodity}. The margins are modest and the risks are known. I prefer it so."),
    ("cargo", "pilot", "sly", "Cargo? {commodity}. Officially {units} units. The manifest and I have an understanding."),
    ("cargo", "pilot", "sly", "A hold of {commodity} bound for {dest}, where they'll pay {dest_price} and never ask where it came from."),
    ("cargo", "pilot", "sly", "What's in the hold is {commodity}. What's under the hold is none of your business."),
    # ------------------------------------------------------------ vendor market talk
    ("market", "vendor", "gruff", "Short on {want}, long on {glut}. Same as the board says. Read the board."),
    ("market", "vendor", "gruff", "The market's the market. It doesn't care what you think of it and neither do I."),
    ("market", "vendor", "gruff", "Prices move when ships dock. You docked. Congratulations, you moved them."),
    ("market", "vendor", "cheerful", "We need {want} and we're swimming in {glut}. Bring one, take the other, everybody's happy!"),
    ("market", "vendor", "cheerful", "Trade's been lively! Three hulls this week. Well, two and a half. One of them barely counted."),
    ("market", "vendor", "cheerful", "The trick is to buy the green and sell the orange. I made that up but it works."),
    ("market", "vendor", "nervous", "We're low on {want}. I keep telling them. They keep saying a ship is coming."),
    ("market", "vendor", "nervous", "The {glut} is going to spoil if nobody buys it. Can {glut} spoil? I should check."),
    ("market", "vendor", "nervous", "Prices swing so fast here. I put a number up and it's wrong before the ink dries."),
    ("market", "vendor", "formal", "{station} imports {want} and exports {glut}. Our rates reflect both."),
    ("market", "vendor", "formal", "Every trade moves the price a little. Large lots move it a great deal. Plan your volumes."),
    ("market", "vendor", "formal", "Our stock replenishes on the daily cycle. Patience is occasionally the cheaper option."),
    ("market", "vendor", "sly", "Buy {glut} here, sell it where they're short. I'd tell you where, but that costs extra."),
    ("market", "vendor", "sly", "The board's a suggestion. The real price is whatever the last captain was dumb enough to pay."),
    ("market", "vendor", "sly", "We want {want}. Badly. Try not to look like you know that when you sell it."),
    # ------------------------------------------------------------ docking requests
    ("dock_accept", "pilot", "gruff", "Fine. Dock. Don't scratch anything."),
    ("dock_accept", "pilot", "gruff", "You've got ten minutes of my patience. Clock's running."),
    ("dock_accept", "pilot", "gruff", "Come alongside then. Slowly. I've seen how {hull} pilots park."),
    ("dock_accept", "pilot", "cheerful", "Yes! Absolutely! Hatch is cycling. Bring stories."),
    ("dock_accept", "pilot", "cheerful", "Dock away! I'll put the kettle on. It's a very small kettle."),
    ("dock_accept", "pilot", "cheerful", "A guest! Come aboard, come aboard, mind the plant."),
    ("dock_accept", "pilot", "nervous", "Okay. Okay. You can dock. Just... gently. Please."),
    ("dock_accept", "pilot", "nervous", "I suppose it's fine. You don't look dangerous. You don't, do you?"),
    ("dock_accept", "pilot", "nervous", "Alright, hatch is open. I'm keeping the inner door locked though. No offence."),
    ("dock_accept", "pilot", "formal", "Docking approved. Match velocities within tolerance and proceed."),
    ("dock_accept", "pilot", "formal", "You may come alongside. I will hold this orbit until you are clear."),
    ("dock_accept", "pilot", "formal", "Granted. Welcome aboard the {ship}."),
    ("dock_accept", "pilot", "sly", "Sure, dock. What could possibly go wrong."),
    ("dock_accept", "pilot", "sly", "Come aboard. Leave your assumptions at the hatch."),
    ("dock_accept", "pilot", "sly", "I'll allow it. I'm curious what you think you'll find."),
    ("dock_refuse", "pilot", "gruff", "No. Go dock with someone who cares."),
    ("dock_refuse", "pilot", "gruff", "Not today. Not tomorrow either, probably."),
    ("dock_refuse", "pilot", "gruff", "I've got a schedule and it doesn't have you in it."),
    ("dock_refuse", "pilot", "gruff", "Back off. I don't take visitors mid-run."),
    ("dock_refuse", "pilot", "nervous", "No! No, I mean, no thank you. Please keep your distance. Please."),
    ("dock_refuse", "pilot", "nervous", "I don't dock with strangers. I don't dock with friends either, I don't have any. Sorry."),
    ("dock_refuse", "pilot", "nervous", "Why do you want to dock? What did I do? Just, no. Not today."),
    ("dock_refuse", "pilot", "nervous", "My hatch is... broken. Yes. Broken. Try another ship."),
    ("dock_refuse", "pilot", "nervous", "I'd rather not. You could be anyone. Anyone could be anyone."),
    ("dock_refuse", "pilot", "formal", "Regrettably I must decline. My cargo is under bond and the hatch stays sealed."),
    ("dock_refuse", "pilot", "formal", "Not at this time, captain. Perhaps at {dest}."),
    ("dock_refuse", "pilot", "formal", "I am not receiving visitors on this leg. Good day."),
    ("dock_refuse", "pilot", "sly", "Tempting. But no. I like my orbit the way it is."),
    ("dock_refuse", "pilot", "sly", "Dock? With you? I don't even know what you're carrying. That's usually my line."),
    ("dock_refuse", "pilot", "sly", "Ask me again when I'm not carrying anything I'd have to explain."),
    ("dock_refuse", "pilot", "sly", "Not today. Today I'm somebody else's problem."),
    ("dock_refuse", "pilot", "any", "Negative. Keep your distance."),
    ("dock_refuse", "pilot", "any", "Hatch is sealed. Try the station."),
    ("dock_refuse", "pilot", "any", "I'll pass. Nothing personal."),
    ("dock_refuse", "pilot", "any", "Not now. I'm burning in an hour and I want the lane clear."),
    # ------------------------------------------------------------ trade opening
    ("trade_open", "pilot", "gruff", "The {commodity} is {price} a unit. That's the number. It doesn't get smaller by staring."),
    ("trade_open", "pilot", "gruff", "You want my {commodity}? {price} each. Or sell me some, I'll pay what {origin} pays, near enough."),
    ("trade_open", "pilot", "cheerful", "Ooh, a deal! I've got {commodity} at {price}, and if you've got any yourself I'll buy it, hold permitting!"),
    ("trade_open", "pilot", "cheerful", "Let's trade! {commodity} at {price} a unit. I'd shake on it but my hands are covered in coolant."),
    ("trade_open", "pilot", "nervous", "I could sell some {commodity}. {price} each? Is that fair? I think that's fair. Tell me if it isn't. Actually don't."),
    ("trade_open", "pilot", "nervous", "It's {price} per unit of {commodity}. I need to make {dest_price} at {dest} or I'm in trouble. More trouble."),
    ("trade_open", "pilot", "formal", "I can release {commodity} at {price} per unit, or purchase the same at a fair rate, within the limits of my hold."),
    ("trade_open", "pilot", "formal", "My terms: {commodity} at {price}. I do not haggle for sport, but I will hear an offer."),
    ("trade_open", "pilot", "sly", "It's {commodity}, {price} a unit. That's my friendly price. You should see my other one."),
    ("trade_open", "pilot", "sly", "I'll sell {commodity} at {price}. I'll buy it too, if you're foolish enough to sell it to me here."),
    # ------------------------------------------------------------ trade opening, empty hold
    ("trade_open_buy", "pilot", "gruff", "Hold's empty. I'll buy {commodity} at {price} if you've got it. Otherwise we're done here."),
    ("trade_open_buy", "pilot", "cheerful", "Nothing to sell, sorry! But I'm buying {commodity} at {price} a unit if you've got any spare."),
    ("trade_open_buy", "pilot", "nervous", "I don't have anything aboard. I could buy {commodity} though? At {price}? If that's alright?"),
    ("trade_open_buy", "pilot", "formal", "My hold is empty at present. I will purchase {commodity} at {price} per unit, within my means."),
    ("trade_open_buy", "pilot", "sly", "Empty hold. Funny how that happens. I'll take {commodity} off your hands at {price}, though."),
    ("trade_open_buy", "pilot", "any", "Nothing aboard to sell, but I'm buying {commodity} at {price}."),
    # ------------------------------------------------------------ haggling
    ("haggle_accept", "pilot", "gruff", "Fine. Take it. Don't tell anyone I went soft."),
    ("haggle_accept", "pilot", "gruff", "You drive a hard bargain for someone with a hull that size. Done."),
    ("haggle_accept", "pilot", "gruff", "Alright, alright. Lower it is. Now buy something."),
    ("haggle_accept", "pilot", "cheerful", "Oh go on then! For you. Because you asked nicely."),
    ("haggle_accept", "pilot", "cheerful", "Deal! I was going to offer that anyway, I just like watching people ask."),
    ("haggle_accept", "pilot", "cheerful", "Sure! What's a few credits between two people stuck in the same gravity well."),
    ("haggle_accept", "pilot", "nervous", "Yes, fine, okay, lower, just... don't leave without buying. Please."),
    ("haggle_accept", "pilot", "nervous", "I can do that. I think I can do that. Yes. Done."),
    ("haggle_accept", "pilot", "nervous", "Okay. Okay. A bit less. Just stop looking at the hatch like that."),
    ("haggle_accept", "pilot", "formal", "A reasonable request. I will adjust the price accordingly."),
    ("haggle_accept", "pilot", "formal", "Agreed. Consider it a courtesy between professionals."),
    ("haggle_accept", "pilot", "formal", "Very well. The revised rate stands for this conversation only."),
    ("haggle_accept", "pilot", "sly", "Ha. Fine. I like you. That's going to cost me one day."),
    ("haggle_accept", "pilot", "sly", "You know what, yes. I'll make it back on the next fool."),
    ("haggle_accept", "pilot", "sly", "Lower it is. Remember this the next time I need a favour."),
    ("haggle_refuse", "pilot", "gruff", "No. The number's the number."),
    ("haggle_refuse", "pilot", "gruff", "Do I look like a charity? Pay it or leave it."),
    ("haggle_refuse", "pilot", "gruff", "I've had this argument with better pilots than you. They lost too."),
    ("haggle_refuse", "pilot", "cheerful", "Aw, I wish I could! But {dest} is counting on me, and so is my rent."),
    ("haggle_refuse", "pilot", "cheerful", "No can do, friend! But I'll throw in a story for free. Later. Maybe."),
    ("haggle_refuse", "pilot", "cheerful", "Sorry! Price stays. I'm cheerful, not stupid."),
    ("haggle_refuse", "pilot", "nervous", "I can't. I really can't. I've done the sums. Twice. Three times."),
    ("haggle_refuse", "pilot", "nervous", "If I go lower I don't make my margin and then I have to explain to... no. No. Sorry."),
    ("haggle_refuse", "pilot", "nervous", "Please don't push. The price is the price. I'm not good at this."),
    ("haggle_refuse", "pilot", "formal", "I must decline. The rate reflects my costs and my costs are not negotiable."),
    ("haggle_refuse", "pilot", "formal", "The offer stands as made. I would not insult you with a worse one."),
    ("haggle_refuse", "pilot", "formal", "No. But I appreciate the attempt was made politely."),
    ("haggle_refuse", "pilot", "sly", "Nice try. I've used that one myself."),
    ("haggle_refuse", "pilot", "sly", "Lower? Captain, this is already the price I give people I like."),
    ("haggle_refuse", "pilot", "sly", "No. But ask again with a better hull and we'll see."),
    # ------------------------------------------------------------ deal outcomes
    ("deal_done", "pilot", "gruff", "Done. Crates are yours. Get them off my deck."),
    ("deal_done", "pilot", "gruff", "Paid. Good. Now we're both busy."),
    ("deal_done", "pilot", "gruff", "That's settled. Anything else, or can I get back to flying?"),
    ("deal_done", "pilot", "cheerful", "Wonderful! Pleasure doing business. I mean that. Mostly."),
    ("deal_done", "pilot", "cheerful", "Deal done! I'll remember you as the {hull} with the good manners."),
    ("deal_done", "pilot", "cheerful", "Lovely. That's the hold lighter and my mood heavier. Wait. The other way round."),
    ("deal_done", "pilot", "nervous", "Okay. It's done. It went fine. See, it went fine."),
    ("deal_done", "pilot", "nervous", "Thank you. Really. Thank you. You can go now. Sorry. Not like that."),
    ("deal_done", "pilot", "nervous", "Transferred. Counted. Twice. We're good. We're good."),
    ("deal_done", "pilot", "formal", "The transfer is complete and recorded. A pleasure, captain."),
    ("deal_done", "pilot", "formal", "Settled. I shall note the {hull} as a fair trading partner."),
    ("deal_done", "pilot", "formal", "Concluded. May your margins be as clean as your docking."),
    ("deal_done", "pilot", "sly", "Done. You got a good deal. Probably. I'd have to check."),
    ("deal_done", "pilot", "sly", "And that's that. If anyone asks, we never met."),
    ("deal_done", "pilot", "sly", "Pleasure. Now you owe me one, by the rules of the lane. I'll collect."),
    ("no_deal", "pilot", "gruff", "Then we're done talking about it."),
    ("no_deal", "pilot", "gruff", "Suit yourself. {dest} will take it."),
    ("no_deal", "pilot", "cheerful", "No worries! Maybe next orbit."),
    ("no_deal", "pilot", "cheerful", "That's alright. It was nice to have someone to not sell to."),
    ("no_deal", "pilot", "nervous", "Oh. Okay. That's fine. That's... yes. Fine."),
    ("no_deal", "pilot", "nervous", "Right. No deal. I'll just... keep it then. All of it."),
    ("no_deal", "pilot", "formal", "Understood. The offer remains open until I undock."),
    ("no_deal", "pilot", "formal", "As you wish. No harm done on either side."),
    ("no_deal", "pilot", "sly", "Your loss. Or mine. Hard to say yet."),
    ("no_deal", "pilot", "sly", "Fine. I wasn't going to give you the good crates anyway."),
    # ------------------------------------------------------------ farewells
    ("farewell", "any", "gruff", "Go on. Clear my lane."),
    ("farewell", "any", "gruff", "Don't come back unless you're buying."),
    ("farewell", "any", "gruff", "Right. Mind the {star} on your way out."),
    ("farewell", "any", "gruff", "That's enough talking for one week."),
    ("farewell", "any", "gruff", "Undock clean. I'll be watching."),
    ("farewell", "any", "cheerful", "Safe burns! Come find me again, I'll have new stories."),
    ("farewell", "any", "cheerful", "Bye now! Give my regards to whoever's at {nearby}."),
    ("farewell", "any", "cheerful", "Off you go! Watch your periapsis, I'd hate to lose a good listener."),
    ("farewell", "any", "cheerful", "Clear skies, or, well, clear vacuum!"),
    ("farewell", "any", "cheerful", "Take care of that {hull}. It's a Gerald. Geralds need love."),
    ("farewell", "any", "nervous", "Okay. Goodbye. Undock gently. Gently!"),
    ("farewell", "any", "nervous", "Bye. Sorry. Thank you. Sorry."),
    ("farewell", "any", "nervous", "You'll be fine. I'll be fine. Everyone's fine. Go."),
    ("farewell", "any", "nervous", "Please match velocity before you release. Please."),
    ("farewell", "any", "nervous", "That wasn't so bad. Was it? It wasn't. Goodbye."),
    ("farewell", "any", "formal", "Good day, captain. Fly well."),
    ("farewell", "any", "formal", "Until next time. I wish you a clean approach and a fair price."),
    ("farewell", "any", "formal", "Safe voyage. Mind the heat line."),
    ("farewell", "any", "formal", "Farewell. You have my thanks for the courtesy."),
    ("farewell", "any", "formal", "Goodbye. The hatch will seal thirty seconds after you release."),
    ("farewell", "any", "sly", "Off you go. Try not to tell anyone what you paid."),
    ("farewell", "any", "sly", "See you around. I'll know before you do."),
    ("farewell", "any", "sly", "Go on. And check your hold before you sell. I'm kidding. Mostly."),
    ("farewell", "any", "sly", "Later, captain. Keep a hatch key spare."),
    ("farewell", "any", "sly", "Until we meet again. We will. It's a small galaxy and I owe you nothing yet."),
    ("farewell", "any", "any", "Safe flying."),
    ("farewell", "any", "any", "Clear the lane on your way out."),
    ("farewell", "any", "any", "See you in {system}, or the next one."),
    ("farewell", "any", "any", "Mind the {star}."),
    # ------------------------------------------------------------ vendor extras
    ("farewell", "vendor", "any", "Come back when your hold's empty. Or full. Either works for me."),
    ("farewell", "vendor", "any", "Thanks for stopping at {station}. Tell your friends. Tell your enemies, they have credits too."),
    ("smalltalk", "vendor", "any", "You'd think a station would be quiet. It never is. Something is always venting."),
    ("smalltalk", "vendor", "any", "I've never left {station}. Why would I? Everything interesting docks here eventually."),
    ("smalltalk", "vendor", "any", "The pilots all say the same thing when they land: 'you should see the prices at the last place'. Then they buy anyway."),
    ("smalltalk", "pilot", "any", "I'll be at {dest} in a few days if the burn goes right. Then it's the same thing again the other way."),
    ("smalltalk", "pilot", "any", "This {ship} has done more orbits than I have. I try not to think about what that means."),
    ("smalltalk", "pilot", "any", "Coasting is the job. Burning is the ten percent everyone talks about."),
]


def main():
    out = os.path.join(os.path.dirname(__file__), "..", "assets", "dialog", "lines.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    lines = [{"cat": c, "who": w, "mood": m, "text": t} for c, w, m, t in L]
    with open(out, "w") as f:
        json.dump({"lines": lines}, f, indent=1, ensure_ascii=False)
    cats = {}
    for c, *_ in L:
        cats[c] = cats.get(c, 0) + 1
    print(len(L), "lines:", cats)


if __name__ == "__main__":
    main()
